export const SET_TYPE_ORDER = 'SET_TYPE_ORDER';
export const SET_OBJECT = 'SET_OBJECT';
export const SET_DATE = 'SET_DATE';
export const SET_M_OR_W = 'SET_M_OR_W';
export const SET_REGISTRATION_NUMBER = 'SET_REGISTRATION_NUMBER';
export const SET_NAME_SELLER = 'SET_NAME_SELLER';
export const SET_ADDRESS_SELLER = 'SET_ADDRESS_SELLER';